name: FE build Admin console

on:
    push:
        branches:
            - '**'
        tags-ignore:
            - 'dockerImage.v.*'

jobs:
    build:
        name: Build & Release
        if: "!contains(github.event.head_commit.author, 'action@github.com')"
        runs-on: ubuntu-latest
        steps:
            - name: set env
              run: echo BRANCH=$(echo -n "${GITHUB_REF#refs/heads/}") >> $GITHUB_ENV
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v2
              with:
                  node-version: 14.18.3
            - run: yarn install --frozen-lockfile
              env:
                  GITHUB_TOKEN: ${{ secrets.github_token }}
            - name: Run linters
              uses: wearerequired/lint-action@v1
              with:
                  github_token: ${{ secrets.github_token }}
                  eslint: true
                  eslint_dir: ./
                  eslint_extensions: js,ts,tsx
                  prettier: true
            - name: test and build
              run: |
                  echo "127.0.0.1 localhost" | sudo tee -a /etc/hosts
                  echo "fs.inotify.max_user_watches=524288" | sudo tee -a /etc/sysctl.conf
                  # need to change tests to mocked data: yarn run test:integration:cli
                  yarn run build
              env:
                  GITHUB_TOKEN: ${{ secrets.github_token }}
            - name: Bump version
              if: env.BRANCH == 'release'
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  yarn run release
              env:
                  GITHUB_TOKEN: ${{ secrets.github_token }}
            - name: Push changes
              if: env.BRANCH == 'release'
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{env.BRANCH}}
                  force: true
                  tags: true
            - uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: cypress-videos
                  path: cypress
